package main

//
// DO NOT EDIT THIS FILE
// This file is automatically generated from the Makefile
//
// make ValidateTables.go
//

import (
	"fmt"
	"os"
)

func ValidateTablesDDL() {
	var err error

	// Table: t_email_q
	/* {
		"created": true,
		"error_msg": true,
		"final_body_html": true,
		"final_body_text": true,
		"final_subject": true,
		"final_to": true,
		"id": true,
		"input_data": true,
		"sent_at": true,
		"seq": true,
		"status": true,
		"template_file_name": true,
		"updated": true,
		"user_id": true
	} */

	err = PGCheckTableColumns(PGTable{
		TableName: "t_email_q",
		Columns: []PGColumn{
			{ColumnName: "seq"},
			{ColumnName: "input_data"},
			{ColumnName: "final_body_text"},
			{ColumnName: "id"},
			{ColumnName: "error_msg"},
			{ColumnName: "final_to"},
			{ColumnName: "final_subject"},
			{ColumnName: "sent_at"},
			{ColumnName: "created"},
			{ColumnName: "user_id"},
			{ColumnName: "status"},
			{ColumnName: "template_file_name"},
			{ColumnName: "final_body_html"},
			{ColumnName: "updated"},
		},
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Missing %s - PG not setup correctly.  Table missing column or missing.\n", err)
		os.Exit(1)
	}

}
